version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: sqlalchemy
    versions:
    - 1.3.22
    - 1.3.23
    - 1.4.0
    - 1.4.1
    - 1.4.2
    - 1.4.3
    - 1.4.4
    - 1.4.5
    - 1.4.6
    - 1.4.7
    - 1.4.8
    - 1.4.9
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: tox
    versions:
    - 3.21.3
    - 3.21.4
    - 3.22.0
  - dependency-name: virtualenv
    versions:
    - 20.4.0
    - 20.4.1
  - dependency-name: amqp
    versions:
    - 5.0.5
- package-ecosystem: npm
  directory: "/portal"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
    - 5.2.2
  - dependency-name: acorn
    versions:
    - 8.0.5
    - 8.1.0
    - 8.1.1
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: i18next-conv
    versions:
    - 10.1.0
  - dependency-name: replace-in-file
    versions:
    - 6.1.0
