"""empty message

Revision ID: 2ddfab3c6533
Revises: 2214f33d3a7b
Create Date: 2016-01-28 12:01:06.774836

"""

# revision identifiers, used by Alembic.
revision = '2ddfab3c6533'
down_revision = '2214f33d3a7b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locale', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'locale')
    ### end Alembic commands ###
