"""empty message

Revision ID: c4a89e579e00
Revises: 12113d3fcab1
Create Date: 2016-06-08 19:39:22.067943

"""

# revision identifiers, used by Alembic.
revision = 'c4a89e579e00'
down_revision = '12113d3fcab1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tou',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tou')
    ### end Alembic commands ###
