from alembic import op
from sqlalchemy.sql import text

from portal.system_uri import (
    PRACTICE_REGION,
    SHORTCUT_ALIAS,
    SHORTNAME_ID
)


"""Delete orphaned organization identifiers

Revision ID: 00b081faf417
Revises: 8ecdd6381235
Create Date: 2017-12-26 16:42:12.969440

"""

# revision identifiers, used by Alembic.
revision = '00b081faf417'
down_revision = '8ecdd6381235'


def upgrade():
    conn = op.get_bind()
    query = (
        "select identifiers.id, value, system from identifiers "
        "where system = :identifier and identifiers.id "
        "not in (select identifier_id from organization_identifiers)")

    kill_ids = set()
    for identifier in (PRACTICE_REGION, SHORTCUT_ALIAS, SHORTNAME_ID):
        results = conn.execute(text(query), identifier=identifier).fetchall()
        kill_ids.update([r[0] for r in results])

    # without any, we're done
    if not kill_ids:
        return

    # found strange case where one of these ids was set on test user
    # 10021 | phoenixa@gmail.com | Tony | PhoenixInterventionStaffRemoved
    query = "delete from user_identifiers where identifier_id in :identifiers"
    conn.execute(text(query), identifiers=tuple(kill_ids))

    # purge the list
    query = "delete from identifiers where id in :identifiers"
    conn.execute(text(query), identifiers=tuple(kill_ids))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
