"""add patient_list table for paginated /patients view

Revision ID: 038a1a5f4218
Revises: daee63f50d35
Create Date: 2024-09-30 16:10:26.216512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038a1a5f4218'
down_revision = 'daee63f50d35'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('questionnaire_status', sa.Text(), nullable=True),
    sa.Column('visit', sa.Text(), nullable=True),
    sa.Column('study_id', sa.Text(), nullable=True),
    sa.Column('consent_date', sa.DateTime(), nullable=True),
    sa.Column('sites', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('test_role', sa.Boolean(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_list_birthdate'), 'patient_list', ['birthdate'], unique=False)
    op.create_index(op.f('ix_patient_list_consent_date'), 'patient_list', ['consent_date'], unique=False)
    op.create_index(op.f('ix_patient_list_email'), 'patient_list', ['email'], unique=False)
    op.create_index(op.f('ix_patient_list_first_name'), 'patient_list', ['first_name'], unique=False)
    op.create_index(op.f('ix_patient_list_last_name'), 'patient_list', ['last_name'], unique=False)
    op.create_index(op.f('ix_patient_list_questionnaire_status'), 'patient_list', ['questionnaire_status'], unique=False)
    op.create_index(op.f('ix_patient_list_sites'), 'patient_list', ['sites'], unique=False)
    op.create_index(op.f('ix_patient_list_study_id'), 'patient_list', ['study_id'], unique=False)
    op.create_index(op.f('ix_patient_list_visit'), 'patient_list', ['visit'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_list_visit'), table_name='patient_list')
    op.drop_index(op.f('ix_patient_list_study_id'), table_name='patient_list')
    op.drop_index(op.f('ix_patient_list_sites'), table_name='patient_list')
    op.drop_index(op.f('ix_patient_list_questionnaire_status'), table_name='patient_list')
    op.drop_index(op.f('ix_patient_list_last_name'), table_name='patient_list')
    op.drop_index(op.f('ix_patient_list_first_name'), table_name='patient_list')
    op.drop_index(op.f('ix_patient_list_email'), table_name='patient_list')
    op.drop_index(op.f('ix_patient_list_consent_date'), table_name='patient_list')
    op.drop_index(op.f('ix_patient_list_birthdate'), table_name='patient_list')
    op.drop_table('patient_list')
    # ### end Alembic commands ###
