"""add patient_list table for paginated /patients view

Revision ID: 038a1a5f4218
Revises: daee63f50d35
Create Date: 2024-09-30 16:10:26.216512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038a1a5f4218'
down_revision = 'daee63f50d35'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_list',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Text(), nullable=True),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('questionnaire_status', sa.Text(), nullable=True),
    sa.Column('empro_status', sa.Text(), nullable=True),
    sa.Column('clinician', sa.Text(), nullable=True),
    sa.Column('action_state', sa.Text(), nullable=True),
    sa.Column('visit', sa.Text(), nullable=True),
    sa.Column('empro_visit', sa.Text(), nullable=True),
    sa.Column('consentdate', sa.DateTime(), nullable=True),
    sa.Column('empro_consentdate', sa.DateTime(), nullable=True),
    sa.Column('org_name', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('test_role', sa.Boolean(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_index(op.f('ix_patient_list_action_state'), 'patient_list', ['action_state'], unique=False)
    op.create_index(op.f('ix_patient_list_birthdate'), 'patient_list', ['birthdate'], unique=False)
    op.create_index(op.f('ix_patient_list_clinician'), 'patient_list', ['clinician'], unique=False)
    op.create_index(op.f('ix_patient_list_consentdate'), 'patient_list', ['consentdate'], unique=False)
    op.create_index(op.f('ix_patient_list_email'), 'patient_list', ['email'], unique=False)
    op.create_index(op.f('ix_patient_list_empro_consentdate'), 'patient_list', ['empro_consentdate'], unique=False)
    op.create_index(op.f('ix_patient_list_empro_status'), 'patient_list', ['empro_status'], unique=False)
    op.create_index(op.f('ix_patient_list_empro_visit'), 'patient_list', ['empro_visit'], unique=False)
    op.create_index(op.f('ix_patient_list_firstname'), 'patient_list', ['firstname'], unique=False)
    op.create_index(op.f('ix_patient_list_lastname'), 'patient_list', ['lastname'], unique=False)
    op.create_index(op.f('ix_patient_list_org_name'), 'patient_list', ['org_name'], unique=False)
    op.create_index(op.f('ix_patient_list_questionnaire_status'), 'patient_list', ['questionnaire_status'], unique=False)
    op.create_index(op.f('ix_patient_list_study_id'), 'patient_list', ['study_id'], unique=False)
    op.create_index(op.f('ix_patient_list_visit'), 'patient_list', ['visit'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_list_visit'), table_name='patient_list')
    op.drop_index(op.f('ix_patient_list_study_id'), table_name='patient_list')
    op.drop_index(op.f('ix_patient_list_questionnaire_status'), table_name='patient_list')
    op.drop_index(op.f('ix_patient_list_org_name'), table_name='patient_list')
    op.drop_index(op.f('ix_patient_list_lastname'), table_name='patient_list')
    op.drop_index(op.f('ix_patient_list_firstname'), table_name='patient_list')
    op.drop_index(op.f('ix_patient_list_empro_visit'), table_name='patient_list')
    op.drop_index(op.f('ix_patient_list_empro_status'), table_name='patient_list')
    op.drop_index(op.f('ix_patient_list_empro_consentdate'), table_name='patient_list')
    op.drop_index(op.f('ix_patient_list_email'), table_name='patient_list')
    op.drop_index(op.f('ix_patient_list_consentdate'), table_name='patient_list')
    op.drop_index(op.f('ix_patient_list_clinician'), table_name='patient_list')
    op.drop_index(op.f('ix_patient_list_birthdate'), table_name='patient_list')
    op.drop_index(op.f('ix_patient_list_action_state'), table_name='patient_list')
    op.drop_table('patient_list')
    # ### end Alembic commands ###
