"""empty message

Revision ID: 09e3e4ac683b
Revises: 5d1daa0f3a14
Create Date: 2017-05-04 15:06:57.076916

"""

# revision identifiers, used by Alembic.
revision = '09e3e4ac683b'
down_revision = '5d1daa0f3a14'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('alt_phone', sa.String(length=40), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'alt_phone')
    ### end Alembic commands ###
