"""empty message

Revision ID: 0fa4a0bd6595
Revises: b68a125b8470
Create Date: 2017-03-07 19:12:13.758000

"""

# revision identifiers, used by Alembic.
revision = '0fa4a0bd6595'
down_revision = 'b68a125b8470'

from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("commit")  # get around transaction warnings by faking a commit
    op.execute(
        "ALTER TYPE auth_methods ADD VALUE IF NOT EXISTS 'service_token_authenticated'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
