"""empty message

Revision ID: 1057f3f25ff9
Revises: c04d7e1c0ae
Create Date: 2016-03-30 08:29:01.521976

"""

# revision identifiers, used by Alembic.
revision = '1057f3f25ff9'
down_revision = 'c04d7e1c0ae'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'users_phone_key', 'users', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'users_phone_key', 'users', ['phone'])
    ### end Alembic commands ###
