"""empty message

Revision ID: 106e3631fe9
Revises: 156d9b04d4bc
Create Date: 2015-06-22 18:50:39.081374

"""

# revision identifiers, used by Alembic.
revision = '106e3631fe9'
down_revision = '156d9b04d4bc'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthdate', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birthdate')
    ### end Alembic commands ###
