from alembic import op
import sqlalchemy as sa


"""empty message

Revision ID: 13a45e9375d7
Revises: 87014965d131
Create Date: 2018-02-01 13:34:09.675188

"""

# revision identifiers, used by Alembic.
revision = '13a45e9375d7'
down_revision = '87014965d131'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practitioners', sa.Column('email', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practitioners', 'email')
    # ### end Alembic commands ###
