"""empty message

Revision ID: 13d1c714823a
Revises: 462ac1b607e9
Create Date: 2017-01-18 17:27:50.282970

"""

# revision identifiers, used by Alembic.
revision = '13d1c714823a'
down_revision = '462ac1b607e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM auth_providers WHERE user_id is NULL")
    op.alter_column('auth_providers', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_providers', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
