"""Add user_consent.research_study_id

Revision ID: 1977c23a53c8
Revises: bb82a0b6cb5c
Create Date: 2020-08-03 14:43:48.170252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1977c23a53c8'
down_revision = 'bb82a0b6cb5c'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user_consents',
        sa.Column('research_study_id', sa.Integer()))
    op.execute('UPDATE user_consents SET research_study_id = 0')
    op.alter_column('user_consents', 'research_study_id', nullable=False)
    op.create_index(
        op.f('ix_user_consents_user_id'),
        'user_consents',
        ['user_id'],
        unique=False)
    op.create_foreign_key(
        None,
        'user_consents',
        'research_studies',
        ['research_study_id'],
        ['id'],
        ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'user_consents_research_study_id_fkey',
        'user_consents',
        type_='foreignkey')
    op.drop_index(
        op.f('ix_user_consents_user_id'), table_name='user_consents')
    op.drop_column('user_consents', 'research_study_id')
    # ### end Alembic commands ###
