"""empty message

Revision ID: 1a0225311859
Revises: 38cfbd643c73
Create Date: 2017-06-12 17:08:32.310777

"""

# revision identifiers, used by Alembic.
revision = '1a0225311859'
down_revision = '38cfbd643c73'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_documents', sa.Column(
        'intervention_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_documents', 'interventions', [
                          'intervention_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_documents', type_='foreignkey')
    op.drop_column('user_documents', 'intervention_id')
    # ### end Alembic commands ###
