"""empty message

Revision ID: 1ab82c60f309
Revises: 31d8a967049f
Create Date: 2017-02-09 14:06:56.873501

"""

# revision identifiers, used by Alembic.
revision = '1ab82c60f309'
down_revision = '31d8a967049f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('coding_options', sa.Integer()))
    op.execute('update organizations set coding_options = 14')
    op.alter_column('organizations', 'coding_options', nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'coding_options')
    ### end Alembic commands ###
