"""empty message

Revision ID: 1df2ef1f5b73
Revises: 30e217c5c0c0
Create Date: 2015-10-13 12:04:57.609157

"""

# revision identifiers, used by Alembic.
revision = '1df2ef1f5b73'
down_revision = '30e217c5c0c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    connection = None
    if not op.get_context().as_sql:
        connection = op.get_bind()
        connection.execution_options(isolation_level='AUTOCOMMIT')

    op.execute("ALTER TYPE providers ADD value 'google' after 'facebook'")

    if connection is not None:
        connection.execution_options(isolation_level='READ_COMMITTED')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    error = "Postgres doesn't support dropping enum values "\
            "Remove 'google' from 'providers' type by hand"
    raise ValueError(error)
    ### end Alembic commands ###
