"""empty message

Revision ID: 2214f33d3a7b
Revises: 4599fb6a938a
Create Date: 2016-01-25 03:06:33.974308

"""

# revision identifiers, used by Alembic.
revision = '2214f33d3a7b'
down_revision = '4599fb6a938a'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE users ALTER COLUMN username TYPE VARCHAR(64)')

    command = """
    ALTER TABLE tokens
    DROP CONSTRAINT token_user_id_fkey,
    ADD CONSTRAINT token_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
    """
    op.execute(command)

    command = """
    ALTER TABLE tokens
    DROP CONSTRAINT token_client_id_fkey,
    ADD CONSTRAINT token_client_id_fkey
    FOREIGN KEY (client_id) REFERENCES clients(client_id)
    ON DELETE CASCADE
    """
    op.execute(command)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE users ALTER COLUMN username TYPE VARCHAR(40)')

    command = """
    ALTER TABLE tokens
    DROP CONSTRAINT token_user_id_fkey,
    ADD CONSTRAINT token_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users(id)
    """
    op.execute(command)

    command = """
    ALTER TABLE tokens
    DROP CONSTRAINT token_client_id_fkey,
    ADD CONSTRAINT token_client_id_fkey
    FOREIGN KEY (client_id) REFERENCES clients(client_id)
    """
    op.execute(command)
    ### end Alembic commands ###
