"""empty message

Revision ID: 25d491602bf
Revises: None
Create Date: 2015-06-18 18:32:58.462466

"""

# revision identifiers, used by Alembic.
revision = '25d491602bf'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
