import sqlalchemy as sa
from alembic import op

"""empty message

Revision ID: 26fb7947cd1e
Revises: 93809e7fbe16
Create Date: 2017-08-22 12:13:29.569281

"""

# revision identifiers, used by Alembic.
revision = '26fb7947cd1e'
down_revision = '93809e7fbe16'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaire_banks', sa.Column('intervention_id', sa.Integer(), nullable=True))
    op.alter_column('questionnaire_banks', 'organization_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.create_foreign_key('questionnaire_banks_intervention_id_fkey', 'questionnaire_banks',
                          'interventions', ['intervention_id'], ['id'])
    op.create_check_constraint(
               'ck_qb_intv_org_mutual_exclusion',
               'questionnaire_banks',
               'NOT(organization_id IS NULL AND intervention_id IS NULL) '
               'AND NOT(organization_id IS NOT NULL AND intervention_id IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_qb_intv_org_mutual_exclusion', 'questionnaire_banks')
    op.drop_constraint('questionnaire_banks_intervention_id_fkey', 'questionnaire_banks',
                       type_='foreignkey')
    op.alter_column('questionnaire_banks', 'organization_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_column('questionnaire_banks', 'intervention_id')
    # ### end Alembic commands ###
