"""empty message

Revision ID: 297a2e5d1464
Revises: 23b47479c442
Create Date: 2017-05-24 09:03:06.543629

"""

# revision identifiers, used by Alembic.
revision = '297a2e5d1464'
down_revision = '23b47479c442'

from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'_questionnaire_bank_questionnaire_rank',
                       'questionnaire_bank_questionnaires', type_='unique')
    op.create_unique_constraint(
        '_questionnaire_bank_questionnaire_rank',
        'questionnaire_bank_questionnaires',
        ['questionnaire_bank_id', 'rank'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_questionnaire_bank_questionnaire_rank',
                       'questionnaire_bank_questionnaires', type_='unique')
    op.create_unique_constraint(
        u'_questionnaire_bank_questionnaire_rank',
        'questionnaire_bank_questionnaires', ['questionnaire_id', 'rank'])
    # ### end Alembic commands ###
