"""add 'failsafe' to encounter auth_methods

Revision ID: 29ddc9e0f61d
Revises: a97e02e09733
Create Date: 2019-06-11 12:16:10.433037

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '29ddc9e0f61d'
down_revision = 'a97e02e09733'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("commit")  # get around transaction warnings by faking a commit
    op.execute(
        "ALTER TYPE auth_methods ADD VALUE IF NOT EXISTS 'failsafe'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
