"""MUSIC patients should have access `subscribed`, not `granted`.

Revision ID: 2b127d65388b
Revises: ef6fe47c40d1
Create Date: 2018-05-01 11:49:34.088346

"""
from alembic import op
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '2b127d65388b'
down_revision = 'ef6fe47c40d1'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(text(
        "UPDATE user_interventions SET access='subscribed' "
        "WHERE access='granted' AND intervention_id = ("
        "SELECT id FROM interventions WHERE name = 'music')"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(text(
        "UPDATE user_interventions SET access='granted' "
        "WHERE access='subscribed'"))
    # ### end Alembic commands ###
