"""empty message

Revision ID: 2bde002dd3a9
Revises: cfb3cf41a07a
Create Date: 2016-09-08 12:46:46.429648

"""

# revision identifiers, used by Alembic.
revision = '2bde002dd3a9'
down_revision = 'cfb3cf41a07a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'organizations_email_key',
                       'organizations', type_='unique')
    # One time challenge, brining in the site_persistence model into
    # play - coordinating org IDs is difficult between systems.  Avoid
    # conflicts in the strategies by renaming the exising orgs.  We'll
    # hand migrate current records after importing a common site_persistence.

    conn = op.get_bind()
    result = conn.execute("SELECT id, name FROM organizations where id > 0 "
                          "AND id < 100")
    for row in result:
        if row[1].startswith('was:'):
            continue
        conn.execute(text("UPDATE organizations SET name=:name "
                          "WHERE id=:id"), name='was:' + row[1], id=row[0])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        u'organizations_email_key', 'organizations', ['email'])
    ### end Alembic commands ###
