"""AdherenceData table

Revision ID: 2e9b9e696bb8
Revises: ccb67176c56f
Create Date: 2023-06-15 17:45:43.699277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e9b9e696bb8'
down_revision = 'ccb67176c56f'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adherence_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('rs_id_visit', sa.Text(), nullable=False),
    sa.Column('valid_till', sa.DateTime(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'rs_id_visit', name='_adherence_unique_patient_visit')
    )
    op.create_index(op.f('ix_adherence_data_patient_id'), 'adherence_data', ['patient_id'], unique=False)
    op.create_index(op.f('ix_adherence_data_rs_id_visit'), 'adherence_data', ['rs_id_visit'], unique=False)
    op.create_index(op.f('ix_adherence_data_valid_till'), 'adherence_data', ['valid_till'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adherence_data_valid_till'), table_name='adherence_data')
    op.drop_index(op.f('ix_adherence_data_rs_id_visit'), table_name='adherence_data')
    op.drop_index(op.f('ix_adherence_data_patient_id'), table_name='adherence_data')
    op.drop_table('adherence_data')
    # ### end Alembic commands ###
