"""empty message

Revision ID: 2fdf0e8b8e08
Revises: 7b4733a907f9
Create Date: 2017-08-10 14:32:32.887039

"""

# revision identifiers, used by Alembic.
revision = '2fdf0e8b8e08'
down_revision = '7b4733a907f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        u'scheduled_jobs_name_key', 'scheduled_jobs', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'scheduled_jobs_name_key',
                       'scheduled_jobs', type_='unique')
    # ### end Alembic commands ###
