"""empty message

Revision ID: 31d8a967049f
Revises: 4b1e5b7b69eb
Create Date: 2017-02-07 12:22:10.694675

"""

# revision identifiers, used by Alembic.
revision = '31d8a967049f'
down_revision = '4b1e5b7b69eb'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_identifiers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('identifier_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['identifier_id'], ['identifiers.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_identifiers')
    # ### end Alembic commands ###
