from alembic import op
import sqlalchemy as sa



"""empty message

Revision ID: 34d3472e95dc
Revises: 883fd1095361
Create Date: 2018-11-08 21:46:22.954589

"""

# revision identifiers, used by Alembic.
revision = '34d3472e95dc'
down_revision = '883fd1095361'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qb_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('qb_id', sa.Integer(), nullable=True),
    sa.Column('qb_recur_id', sa.Integer(), nullable=True),
    sa.Column('qb_iteration', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['qb_id'], ['questionnaire_banks.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['qb_recur_id'], ['recurs.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qb_timeline')
    # ### end Alembic commands ###
