"""empty message

Revision ID: 3b655c2d1a85
Revises: 55a29f2ab55d
Create Date: 2015-10-15 16:43:53.324828

"""

# revision identifiers, used by Alembic.
revision = '3b655c2d1a85'
down_revision = '55a29f2ab55d'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # different generations of the db have singular and plural versions
    # query for the constraint name
    query = "select constraint_name from "\
            "INFORMATION_SCHEMA.TABLE_CONSTRAINTS "\
            "where table_name = 'users' and "\
            "constraint_name like '%%_username_key';"
    connection = op.get_bind()
    rs = connection.execute(query, execute_options=None)
    op.drop_constraint(rs.first()[0], 'users', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'user_username_key', 'users', ['username'])
    ### end Alembic commands ###
