"""add user.otp_secret for 2FA

Revision ID: 406484da81af
Revises: 1a84c56e6abc
Create Date: 2021-04-06 15:21:36.057351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406484da81af'
down_revision = '1a84c56e6abc'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_secret', sa.String(length=16)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_secret')
    # ### end Alembic commands ###
