"""empty message

Revision ID: 424f18f4c1df
Revises: 106e3631fe9
Create Date: 2015-06-23 11:31:08.548661

"""

# revision identifiers, used by Alembic.
revision = '424f18f4c1df'
down_revision = '106e3631fe9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM

providers_list = ENUM('facebook', 'twitter', 'truenth', name='providers',
        create_type=False)

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    providers_list.create(op.get_bind(), checkfirst=False)
    op.create_table('auth_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', providers_list, nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_providers')
    providers_list.drop(op.get_bind(), checkfirst=False)
    ### end Alembic commands ###
