"""empty message

Revision ID: 4456ad5faf86
Revises: 521aa70e0617
Create Date: 2015-09-03 19:40:53.744703

"""

# revision identifiers, used by Alembic.
revision = '4456ad5faf86'
down_revision = '521aa70e0617'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('user_roles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['role_id'], ['roles.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column(u'users', sa.Column(
        'confirmed_at', sa.DateTime(), nullable=True))
    op.add_column(u'users', sa.Column('is_active', sa.Boolean(),
                                      server_default='1', nullable=False))
    op.add_column(u'users', sa.Column(
        'password', sa.String(length=255), nullable=True))
    op.add_column(u'users', sa.Column('reset_password_token',
                                      sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'reset_password_token')
    op.drop_column(u'users', 'password')
    op.drop_column(u'users', 'is_active')
    op.drop_column(u'users', 'confirmed_at')
    op.drop_table('user_roles')
    op.drop_table('roles')
    ### end Alembic commands ###
