"""empty message

Revision ID: 462ac1b607e9
Revises: d1d9da22c976
Create Date: 2017-01-11 20:48:25.301069

"""

# revision identifiers, used by Alembic.
revision = '462ac1b607e9'
down_revision = 'd1d9da22c976'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_consents', sa.Column('options', sa.Integer()))
    op.execute('update user_consents set options = 7')
    op.alter_column('user_consents', 'options', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_consents', 'options')
    # ### end Alembic commands ###
