"""encode comorb QuestionnaireResponse answers

Revision ID: 4737a563e3f9
Revises: df233cc6fa8a
Create Date: 2019-12-16 17:45:06.516658

"""
from alembic import op
from sqlalchemy.orm import sessionmaker

from portal.models.questionnaire_response import QuestionnaireResponse
from portal.models.questionnaire import Questionnaire

# revision identifiers, used by Alembic.
revision = '4737a563e3f9'
down_revision = 'df233cc6fa8a'


Session = sessionmaker()


def fixup_comorb(questionnaire_response_json, comorb_options):
    """Replace valueString text with corresponding valueCoding"""
    # exit early if preconditions not met
    if len(questionnaire_response_json['group']['question'][0]['answer']) > 0:
        return questionnaire_response_json

    # JSONB mutation detection work around
    # See https://bugs.launchpad.net/fuel/+bug/1482658
    qnr_json_copy = copy.deepcopy(questionnaire_response_json)

    target_answers = qnr_json_copy['group']['question'][0]['answer']
    coded_answers = []
    for answer in target_answers:
        coded_answer = { 'valueCoding': {
            # lookup code from valueString
            'code': comorb_options[answer['valueString']],
            'system': 'https://eproms.truenth.org/api/codings/assessment',
        }}
        coded_answers.append(coded_answer)

    target_answers = coded_answers
    return qnr_json_copy


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session = Session(bind=op.get_bind())

    instrument_id = 'comorb'
    comorb_q = Questionnaire.find_by_name(name=instrument_id)
    # invert dictionary to lookup code by answer
    comorb_code_map = {v: k for k, v in comorb_q.questionnaire_code_map().items()}

    questionnaire_responses = session.query(QuestionnaireResponse).filter(
        QuestionnaireResponse.document[
            ("questionnaire", "reference")
        ].astext.endswith(instrument_id)
    ).order_by(QuestionnaireResponse.id)

    for qnr in questionnaire_responses:
        qnr_json = fixup_comorb(qnr.document, comorb_options=comorb_code_map)
        if qnr_json == qnr.document:
            continue

        qnr.document = qnr_json
        session.add(qnr)
        session.commit()
        assert qnr.document
        print("Processed QNR: %d" % qnr.id)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
