"""encode comorb QuestionnaireResponse answers

Revision ID: 4737a563e3f9
Revises: df233cc6fa8a
Create Date: 2019-12-16 17:45:06.516658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4737a563e3f9'
down_revision = 'df233cc6fa8a'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
