"""empty message

Revision ID: 491d8352bfc3
Revises: 4364a2938db0
Create Date: 2015-08-13 23:38:29.070618

"""

# revision identifiers, used by Alembic.
revision = '491d8352bfc3'
down_revision = '4364a2938db0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE grants ALTER COLUMN redirect_uri TYPE text')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'ALTER TABLE grants ALTER COLUMN redirect_uri TYPE character varying(255)')
    ### end Alembic commands ###
