from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


"""empty message

Revision ID: 4d5b44069fc5
Revises: 0f1576a4e220
Create Date: 2018-07-10 16:00:55.574363

"""

# revision identifiers, used by Alembic.
revision = '4d5b44069fc5'
down_revision = '0f1576a4e220'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_providers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('auth_providers', sa.Column('token', sqlalchemy_utils.types.json.JSONType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_providers', 'token')
    op.drop_column('auth_providers', 'created_at')
    # ### end Alembic commands ###
