"""empty message

Revision ID: 4f7e2f9ff54e
Revises: a97ce9f7bfc
Create Date: 2015-06-22 14:14:51.036581

"""

# revision identifiers, used by Alembic.
revision = '4f7e2f9ff54e'
down_revision = 'a97ce9f7bfc'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'first_name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column(
        'last_name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column(
        'registered', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'registered')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    ### end Alembic commands ###
