from alembic import op
import sqlalchemy as sa


"""add due field to questionnaire_banks

Revision ID: 50c447197b26
Revises: 9ebdfeb28bef
Create Date: 2017-10-13 09:41:49.941838

"""

# revision identifiers, used by Alembic.
revision = '50c447197b26'
down_revision = '9ebdfeb28bef'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaire_banks', sa.Column('due', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionnaire_banks', 'due')
    # ### end Alembic commands ###
