"""empty message

Revision ID: 510aaa0d1541
Revises: 2cf876dc5770
Create Date: 2016-03-29 10:44:34.942818

"""

# revision identifiers, used by Alembic.
revision = '510aaa0d1541'
down_revision = '2cf876dc5770'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # migration not worth it pre release.  delete codeable_concepts
    # and the many related tables.
    op.execute("DELETE FROM user_observations")
    op.execute("DELETE FROM user_ethnicities")
    op.execute("DELETE FROM user_races")
    op.execute("DELETE FROM observations")
    op.execute("DELETE FROM codeable_concepts")
    op.execute("DELETE FROM value_quantities")

    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('system', sa.String(length=255), nullable=False),
                    sa.Column('code', sa.String(length=80), nullable=False),
                    sa.Column('display', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('system', 'code', name='_system_code')
                    )
    op.create_table('codeable_concept_codings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('codeable_concept_id',
                              sa.Integer(), nullable=False),
                    sa.Column('coding_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['codeable_concept_id'], [
                        'codeable_concepts.id'], ),
                    sa.ForeignKeyConstraint(['coding_id'], ['codings.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column(u'codeable_concepts', sa.Column(
        'text', sa.Text(), nullable=True))
    op.drop_column(u'codeable_concepts', 'code')
    op.drop_column(u'codeable_concepts', 'system')
    op.drop_column(u'codeable_concepts', 'display')
    op.alter_column(u'observations', 'codeable_concept_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column(u'observations', 'value_quantity_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.add_column(u'user_ethnicities', sa.Column(
        'coding_id', sa.Integer(), nullable=False))
    op.alter_column(u'user_ethnicities', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.create_unique_constraint('_ethnicity_user_coding', 'user_ethnicities', [
                                'user_id', 'coding_id'])
    op.drop_constraint(u'user_ethnicities_codeable_concept_id_fkey',
                       'user_ethnicities', type_='foreignkey')
    op.create_foreign_key('user_ethnicities_codings_id_fkey',
                          'user_ethnicities', 'codings', ['coding_id'], ['id'])
    op.drop_column(u'user_ethnicities', 'codeable_concept_id')
    op.alter_column(u'user_observations', 'observation_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column(u'user_observations', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.create_unique_constraint('_user_observation', 'user_observations', [
                                'user_id', 'observation_id'])
    op.add_column(u'user_races', sa.Column(
        'coding_id', sa.Integer(), nullable=False))
    op.alter_column(u'user_races', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.create_unique_constraint('_race_user_coding', 'user_races', [
                                'user_id', 'coding_id'])
    op.drop_constraint(u'user_races_codeable_concept_id_fkey',
                       'user_races', type_='foreignkey')
    op.create_foreign_key('user_races_codings_id_fkey',
                          'user_races', 'codings', ['coding_id'], ['id'])
    op.drop_column(u'user_races', 'codeable_concept_id')
    op.alter_column(u'user_relationships', 'other_user_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column(u'user_relationships', 'relationship_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column(u'user_relationships', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column(u'user_roles', 'role_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column(u'user_roles', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'user_roles', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column(u'user_roles', 'role_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column(u'user_relationships', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column(u'user_relationships', 'relationship_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column(u'user_relationships', 'other_user_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.add_column(u'user_races', sa.Column('codeable_concept_id',
                                           sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('user_races_codings_id_fkey',
                       'user_races', type_='foreignkey')
    op.create_foreign_key(u'user_races_codeable_concept_id_fkey',
                          'user_races', 'codeable_concepts', ['codeable_concept_id'], ['id'])
    op.drop_constraint('_race_user_coding', 'user_races', type_='unique')
    op.alter_column(u'user_races', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_column(u'user_races', 'coding_id')
    op.drop_constraint('_user_observation',
                       'user_observations', type_='unique')
    op.alter_column(u'user_observations', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column(u'user_observations', 'observation_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.add_column(u'user_ethnicities', sa.Column(
        'codeable_concept_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('user_ethnicities_codings_id_fkey',
                       'user_ethnicities', type_='foreignkey')
    op.create_foreign_key(u'user_ethnicities_codeable_concept_id_fkey',
                          'user_ethnicities', 'codeable_concepts', ['codeable_concept_id'], ['id'])
    op.drop_constraint('_ethnicity_user_coding',
                       'user_ethnicities', type_='unique')
    op.alter_column(u'user_ethnicities', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_column(u'user_ethnicities', 'coding_id')
    op.alter_column(u'observations', 'value_quantity_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column(u'observations', 'codeable_concept_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.add_column(u'codeable_concepts', sa.Column(
        'display', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column(u'codeable_concepts', sa.Column(
        'system', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column(u'codeable_concepts', sa.Column(
        'code', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column(u'codeable_concepts', 'text')
    op.drop_table('codeable_concept_codings')
    op.drop_table('codings')
    ### end Alembic commands ###
