"""empty message

Revision ID: 51b83c02eb37
Revises: 2bde002dd3a9
Create Date: 2016-09-29 19:54:11.869397

"""

# revision identifiers, used by Alembic.
revision = '51b83c02eb37'
down_revision = '2bde002dd3a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interventions', sa.Column(
        'display_rank', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interventions', 'display_rank')
    ### end Alembic commands ###
