"""empty message

Revision ID: 533fc09a4d32
Revises: 7793ca45b7f9
Create Date: 2016-12-13 16:14:27.123196

"""

# revision identifiers, used by Alembic.
revision = '533fc09a4d32'
down_revision = '7793ca45b7f9'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tou',
        sa.Column(
            'agreement_url',
            sa.Text(),
            server_default='predates agreement_url',
            nullable=False))
    op.drop_column('tou', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tou', sa.Column('text', sa.TEXT(),
                                   autoincrement=False, nullable=False))
    op.drop_column('tou', 'agreement_url')
    # ### end Alembic commands ###
