"""empty message

Revision ID: 58a9d999ece9
Revises: 0ac4b88c909f
Create Date: 2017-04-26 12:39:32.182048

"""

# revision identifiers, used by Alembic.
revision = '58a9d999ece9'
down_revision = '0ac4b88c909f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_locales',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('organization_id', sa.Integer(), nullable=False),
                    sa.Column('coding_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['coding_id'], ['codings.id'], ),
                    sa.ForeignKeyConstraint(['organization_id'], [
                        'organizations.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('organization_id', 'coding_id',
                                        name='_organization_locale_coding')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_locales')
    ### end Alembic commands ###
