"""empty message

Revision ID: 5a300be640fb
Revises: 038a1a5f4218
Create Date: 2024-10-08 14:34:28.085963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a300be640fb'
down_revision = '038a1a5f4218'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('adherence_data_patient_id_fkey', 'adherence_data')
    op.create_foreign_key(
        'adherence_data_patient_id_fkey',
        'adherence_data',
        'users', ['patient_id'], ['id'], ondelete='cascade')
    op.alter_column('patient_list', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_foreign_key(
        'patient_list_userid_fkey',
        'patient_list',
        'users', ['userid'], ['id'], ondelete='cascade')
    op.drop_constraint('research_data_subject_id_fkey', 'research_data', type_='foreignkey')
    op.create_foreign_key(
        'research_data_subject_id_fkey',
        'research_data',
        'users', ['subject_id'], ['id'], ondelete='cascade')
    op.drop_constraint('research_data_questionnaire_response_id_fkey', 'research_data', type_='foreignkey')
    op.create_foreign_key(
        'research_data_questionnaire_response_id_fkey',
        'research_data',
        'questionnaire_responses', ['questionnaire_response_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('research_data_subject_id_fkey', 'research_data', type_='foreignkey')
    op.create_foreign_key('research_data_subject_id_fkey', 'research_data', 'users', ['subject_id'], ['id'])
    op.drop_constraint('patient_list_userid_fkey', 'patient_list', type_='foreignkey')
    op.alter_column('patient_list', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
