"""Questionnaires gain Identifiers

Revision ID: 5aeadb11e97b
Revises: 91351a73e6e2
Create Date: 2018-03-21 11:44:54.544568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker

from portal.models.identifier import Identifier
from portal.models.questionnaire import QuestionnaireIdentifier
from portal.system_uri import TRUENTH_QUESTIONNAIRE_CODE_SYSTEM

# revision identifiers, used by Alembic.
revision = '5aeadb11e97b'
down_revision = '91351a73e6e2'

Session = sessionmaker()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'questionnaire_identifiers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('questionnaire_id', sa.Integer(), nullable=False),
        sa.Column('identifier_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['identifier_id'], ['identifiers.id'], ondelete='cascade'),
        sa.ForeignKeyConstraint(
            ['questionnaire_id'], ['questionnaires.id'], ondelete='cascade'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'questionnaire_id', 'identifier_id', name='_questionnaire_identifier')
        )

    # prior to dropping name - need to insert and connect identifier for each
    # existing in order to maintain the same questionnaire.id (less deal with
    # the mess of fk constraints)
    bind = op.get_bind()
    session = Session(bind=bind)
    for q_id, name in session.execute("SELECT id, name FROM questionnaires"):
        ident = Identifier(_value=name, system=TRUENTH_QUESTIONNAIRE_CODE_SYSTEM)
        session.add(ident)
        session.commit()
        ident = session.merge(ident)
        q_i = QuestionnaireIdentifier(questionnaire_id=q_id, identifier_id=ident.id)
        session.add(q_i)
    session.commit()

    op.drop_constraint(u'questionnaires_name_key', 'questionnaires', type_='unique')
    op.drop_column(u'questionnaires', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'questionnaires', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    if True:
        raise RuntimeError("This is missing code to pull name field from linked questionnaire_identifiers row")
    op.create_unique_constraint(u'questionnaires_name_key', 'questionnaires', ['name'])
    op.drop_table('questionnaire_identifiers')
    # ### end Alembic commands ###
