"""empty message

Revision ID: 5d7a1030065e
Revises: 823de677d394
Create Date: 2017-06-06 12:36:41.656269

"""

# revision identifiers, used by Alembic.
revision = '5d7a1030065e'
down_revision = '823de677d394'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

Session = sa.orm.sessionmaker()

tou_types = postgresql.ENUM('website terms of use', 'subject website consent',
							'stored website consent form', 'privacy policy',
							name='tou_types', create_type=False)


def upgrade():
    bind = op.get_bind()
    session = Session(bind=bind)

    tou_types.create(bind, checkfirst=False)
    op.add_column('tou', sa.Column('type', tou_types, nullable=True))

    session.execute("UPDATE tou SET type = 'website terms of use'")

    op.alter_column('tou', 'type', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tou', 'type')
    # ### end Alembic commands ###
