"""Timezone questionnaire_response.document['authored']

Revision ID: 64fef97d19ec
Revises: c243aa77e9e4
Create Date: 2021-02-09 16:08:57.722207

"""
from alembic import op
from copy import deepcopy
from datetime import datetime
import json
from sqlalchemy.orm import sessionmaker
from sqlalchemy.sql import text

from portal.date_tools import FHIR_datetime

Session = sessionmaker()

# revision identifiers, used by Alembic.
revision = '64fef97d19ec'
down_revision = 'c243aa77e9e4'


def upgrade():
    """Clean up inconsistent formatting of authored dates"""
    conn = op.get_bind()
    session = Session(bind=conn)
    query = (
        "SELECT id, document FROM questionnaire_responses WHERE"
        " document->>'authored' NOT LIKE '%Z'")
    results = [(row.id, row.document) for row in session.execute(query)]
    update_sql = (
        "UPDATE questionnaire_responses SET document=:document"
        " WHERE questionnaire_responses.id=:qnr_id")
    for qnr_id, document in results:
        dt = FHIR_datetime.parse(document['authored'])
        cp_doc = deepcopy(document)
        cp_doc['authored'] = datetime.strftime(dt, "%Y-%m-%dT%H:%M:%SZ")
        print(f"migrate {document['authored']} to {cp_doc['authored']}")
        conn.execute(text(update_sql), document=json.dumps(cp_doc), qnr_id=qnr_id)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
