"""empty message

Revision ID: 7793ca45b7f9
Revises: bb6381842dea
Create Date: 2016-11-10 10:30:08.259491

"""

# revision identifiers, used by Alembic.
revision = '7793ca45b7f9'
down_revision = 'bb6381842dea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'deleted_id', sa.Integer(), nullable=True))
    op.create_foreign_key('user_deleted_audit_id_fk', 'users', 'audit', [
                          'deleted_id'], ['id'], use_alter=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_deleted_audit_id_fk', 'users', type_='foreignkey')
    op.drop_column('users', 'deleted_id')
    ### end Alembic commands ###
