"""empty message

Revision ID: 7ad0da0d1b72
Revises: af193c376724
Create Date: 2017-07-06 17:42:35.513647

"""

# revision identifiers, used by Alembic.
revision = '7ad0da0d1b72'
down_revision = 'af193c376724'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('days_to_start', sa.Integer(), nullable=False),
                    sa.Column('days_in_cycle', sa.Integer(), nullable=False),
                    sa.Column('days_till_termination',
                              sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table(
        'questionnaire_bank_questionnaire_recurs',
        sa.Column(
            'id',
            sa.Integer(),
            nullable=False),
        sa.Column(
            'questionnaire_bank_questionnaire_id',
            sa.Integer(),
            nullable=False),
        sa.Column(
            'recur_id',
            sa.Integer(),
            nullable=False),
        sa.ForeignKeyConstraint(
            ['questionnaire_bank_questionnaire_id'],
            ['questionnaire_bank_questionnaires.id'],
            ondelete='CASCADE'),
        sa.ForeignKeyConstraint(
            ['recur_id'],
            ['recurs.id'],
            ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'questionnaire_bank_questionnaire_id',
            'recur_id',
            name='_questionnaire_bank_questionnaire_recure'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questionnaire_bank_questionnaire_recurs')
    op.drop_table('recurs')
    # ### end Alembic commands ###
