"""empty message

Revision ID: 85ee128c8304
Revises: 66d8893fe442
Create Date: 2016-05-24 14:36:18.268220

"""

# revision identifiers, used by Alembic.
revision = '85ee128c8304'
down_revision = '66d8893fe442'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identifiers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_use', postgresql.ENUM(
                        'usual', 'official', 'temp', 'secondary', name='id_use'), nullable=True),
                    sa.Column('system', sa.String(length=255), nullable=False),
                    sa.Column('value', sa.Text(), nullable=False),
                    sa.Column('assigner', sa.String(
                        length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('system', 'value',
                                        name='_identifier_system_value')
                    )
    op.create_table('organization_identifiers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('organization_id', sa.Integer(), nullable=False),
                    sa.Column('identifier_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['identifier_id'], ['identifiers.id'], ondelete='cascade'),
                    sa.ForeignKeyConstraint(['organization_id'], [
                        'organizations.id'], ondelete='cascade'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('organization_id', 'identifier_id',
                                        name='_organization_identifier')
                    )
    op.create_unique_constraint('_organization_address', 'organization_addresses', [
                                'organization_id', 'address_id'])
    op.drop_constraint(u'_observation_address',
                       'organization_addresses', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'_observation_address', 'organization_addresses', [
                                'organization_id', 'address_id'])
    op.drop_constraint('_organization_address',
                       'organization_addresses', type_='unique')
    op.drop_table('organization_identifiers')
    op.drop_table('identifiers')
    ### end Alembic commands ###
