 """encode irondemog QuestionnaireResponse answers

Revision ID: 894bbf6a8aa5
Revises: d4517f61aaed
Create Date: 2020-03-12 20:43:49.177994

"""
import copy

from alembic import op
from sqlalchemy.orm import sessionmaker

from portal.models.questionnaire_response import QuestionnaireResponse
from portal.models.questionnaire import Questionnaire

# revision identifiers, used by Alembic.
revision = '894bbf6a8aa5'
down_revision = 'd4517f61aaed'

Session = sessionmaker()


def fixup_qnr(questionnaire_response_json, questionnaire_option_map):
    """Replace valueString text with corresponding valueCoding"""
    # exit early if preconditions not met
    if len(questionnaire_response_json['group']['question'][0]['answer']) == 0:
        return questionnaire_response_json

    # JSONB mutation detection work around
    # See https://bugs.launchpad.net/fuel/+bug/1482658
    qnr_json_copy = copy.deepcopy(questionnaire_response_json)

    target_question = qnr_json_copy['group']['question'][0]
    coded_answers = []
    for answer in target_question['answer']:
        if 'valueCoding' in answer:
            return questionnaire_response_json
        coded_answer = {'valueCoding': {
            # lookup code from valueString
            'code': questionnaire_option_map[answer['valueString']],
            'system': 'https://eproms.truenth.org/api/codings/assessment',
        }}
        coded_answers.append(coded_answer)

    target_question['answer'] = coded_answers
    return qnr_json_copy


def upgrade():
    session = Session(bind=op.get_bind())

    instrument_ids = ('comorb', 'irondemog', 'irondemog_v3')

    for instrument_id in instrument_ids:
        questionnaire = Questionnaire.find_by_name(name=instrument_id)
        # exit if Questionnaire not found
        if not questionnaire:
            return

        # invert dictionary to lookup code by answer
        q_codes = {v: k for k, v in questionnaire.questionnaire_code_map().items()}

        questionnaire_responses = session.query(QuestionnaireResponse).filter(
            QuestionnaireResponse.document[
                ("questionnaire", "reference")
            ].astext.endswith(instrument_id)
        ).order_by(QuestionnaireResponse.id)
        for qnr in questionnaire_responses:
            qnr_json = fixup_qnr(qnr.document, questionnaire_option_map=q_codes)
            if qnr_json == qnr.document:
                continue

            qnr.document = qnr_json
            session.add(qnr)
            session.commit()
            assert qnr.document
            print("Processed QNR: %d" % qnr.id)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
