 """encode irondemog QuestionnaireResponse answers

Revision ID: 894bbf6a8aa5
Revises: d4517f61aaed
Create Date: 2020-03-12 20:43:49.177994

"""
import copy

from alembic import op
from sqlalchemy.orm import sessionmaker

from portal.models.questionnaire_response import QuestionnaireResponse
from portal.models.questionnaire import Questionnaire

# revision identifiers, used by Alembic.
revision = '894bbf6a8aa5'
down_revision = 'd4517f61aaed'

Session = sessionmaker()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
