"""empty message

Revision ID: 8eb3e2e6076a
Revises: 71da0b18ec5f
Create Date: 2026-02-07 01:02:45.622842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb3e2e6076a'
down_revision = '71da0b18ec5f'


def upgrade():
    conn = op.get_bind()

    # Update the living arrangement question
    sql_living_arrangement = sa.sql.text("""
        UPDATE questionnaire_responses qr
        SET document = jsonb_set(
            document,
            '{group,question}',
            (
                SELECT jsonb_agg(
                    CASE
                        WHEN q->>'linkId' = 'irondemog_v3.15' THEN
                            jsonb_set(
                                q,
                                '{answer}',
                                (
                                    SELECT jsonb_agg(
                                        CASE
                                            WHEN a ? 'valueCoding' AND a->'valueCoding'->>'code' = 'irondemog_v3.16.7' THEN
                                                jsonb_set(
                                                    a,
                                                    '{valueCoding,code}',
                                                    '"irondemog_v3.15.7"'::jsonb
                                                )
                                            ELSE a
                                        END
                                    )
                                    FROM jsonb_array_elements(q->'answer') a
                                )
                            )
                        ELSE q
                    END
                )
                FROM jsonb_array_elements(document->'group'->'question') q
            )
        )
        WHERE document->'group'->'question' @> '[{"linkId": "irondemog_v3.15"}]';
    """)
    conn.execute(sql_living_arrangement)

    # Update the supplements question
    sql_supplements = sa.sql.text("""
        UPDATE questionnaire_responses qr
        SET document = jsonb_set(
            document,
            '{group,question}',
            (
                SELECT jsonb_agg(
                    CASE
                        WHEN q->>'linkId' = 'irondemog_v3.25' THEN
                            jsonb_set(
                                q,
                                '{answer}',
                                (
                                    SELECT jsonb_agg(
                                        CASE
                                            WHEN a ? 'valueCoding' AND a->'valueCoding'->>'code' = 'irondemog_v3.26.8' THEN
                                                jsonb_set(
                                                    a,
                                                    '{valueCoding,code}',
                                                    '"irondemog_v3.15.7"'::jsonb
                                                )
                                            ELSE a
                                        END
                                    )
                                    FROM jsonb_array_elements(q->'answer') a
                                )
                            )
                        ELSE q
                    END
                )
                FROM jsonb_array_elements(document->'group'->'question') q
            )
        )
        WHERE document->'group'->'question' @> '[{"linkId": "irondemog_v3.25"}]';
    """)
    conn.execute(sql_supplements)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
