"""empty message

Revision ID: 8eb3e2e6076a
Revises: 71da0b18ec5f
Create Date: 2026-02-07 01:02:45.622842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb3e2e6076a'
down_revision = '71da0b18ec5f'


def upgrade():
    conn = op.get_bind()

    # Fix incorrect valueCoding.code for the living arrangement question.
    # For questions with linkId = 'irondemog_v3.15', replace
    # 'irondemog_v3.16.7' with 'irondemog_v3.15.7'.
    sql_living_arrangement = sa.sql.text("""
        UPDATE questionnaire_responses
        SET document = jsonb_path_replace(
            document,
            '$.group.question[*] ? (@.linkId == "irondemog_v3.15").answer[*].valueCoding.code',
            '"irondemog_v3.15.7"'
        )
        WHERE document @?
            '$.group.question[*] ? (
                @.linkId == "irondemog_v3.15"
                && @.answer[*].valueCoding.code == "irondemog_v3.16.7"
            )';
    """)
    conn.execute(sql_living_arrangement)

    # Fix incorrect valueCoding.code for supplements question.
    # For questions with linkId = 'irondemog_v3.25', replace
    # 'irondemog_v3.26.8' with 'irondemog_v3.15.7'.
    sql_supplements = sa.sql.text("""
        UPDATE questionnaire_responses
        SET document = jsonb_path_replace(
            document,
            '$.group.question[*] ? (@.linkId == "irondemog_v3.25").answer[*].valueCoding.code',
            '"irondemog_v3.15.7"'
        )
        WHERE document @?
            '$.group.question[*] ? (
                @.linkId == "irondemog_v3.25"
                && @.answer[*].valueCoding.code == "irondemog_v3.26.8"
            )';
    """)
    conn.execute(sql_supplements)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
