"""fix ironman demographics codings

Revision ID: 8eb3e2e6076a
Revises: 71da0b18ec5f
Create Date: 2026-02-07 01:02:45.622842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb3e2e6076a'
down_revision = '71da0b18ec5f'

def update_irondemog_codes(document: dict) -> dict:
    """
    Updates the valueCoding.code in the questionnaire_responses document.
    Replace incorrect code for "Other" with correct code

    """
    doc = deepcopy(document)
    questions = doc.get("group", {}).get("question", [])
    for q in questions:
        link_id = q.get("linkId")
        answers = q.get("answer", [])
        for a in answers:
            value_coding = a.get("valueCoding")
            if value_coding and "code" in value_coding:
                # Living arrangement question
                if link_id == "irondemog_v3.15" and value_coding["code"] == "irondemog_v3.16.7":
                    value_coding["code"] = "irondemog_v3.15.7"
                # Supplements question
                if link_id == "irondemog_v3.25" and value_coding["code"] == "irondemog_v3.26.8":
                    value_coding["code"] = "irondemog_v3.25.12"

                # Supplements question
                if link_id == "irondemog.25" and value_coding["code"] == "irondemog.26.8":
                    value_coding["code"] = "irondemog.25.12"
                # Tobacco question
                if link_id == "irondemog.13" and value_coding["code"] == "irondemog.26.8":
                    value_coding["code"] = "irondemog.13.5"
    return doc


def upgrade():
    conn = op.get_bind()

    # Load all questionnaire_responses
    # Load only questionnaire_responses for irondemog questionnaires
    result = conn.execute(sa.text("""
        SELECT id, document
        FROM questionnaire_responses
        WHERE document->'questionnaire'->>'reference' ILIKE '%irondemog'
           OR document->'questionnaire'->>'reference' ILIKE '%irondemog_v3'
    """))
    rows = result.fetchall()

    for row in rows:
        doc_id = row["id"]
        document = row["document"]

        if not document:
            continue

        updated_document = update_irondemog_codes(document)

        # Only update if changed
        if updated_document != document:
            conn.execute(
                sa.text(
                    "UPDATE questionnaire_responses SET document = :document WHERE id = :id"
                ),
                {"document": json.dumps(updated_document), "id": doc_id},
            )
            print("Updated QNR: ", doc_id)



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
