from alembic import op
import sqlalchemy as sa


"""empty message

Revision ID: 8efa45d83a3b
Revises: b4dcf331317e
Create Date: 2018-07-23 12:58:12.567890

"""

# revision identifiers, used by Alembic.
revision = '8efa45d83a3b'
down_revision = 'b4dcf331317e'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
