"""promote __system__ user to admin

Revision ID: 9c6788e6db2f
Revises: c242e22f5a47
Create Date: 2019-08-01 17:28:56.859235

"""
from portal.database import db
from portal.models.user import User
from portal.models.role import Role, ROLE

# revision identifiers, used by Alembic.
revision = '9c6788e6db2f'
down_revision = 'c242e22f5a47'


def upgrade():
    sys_user = User.query.filter_by(email='__system__').one()
    if len(sys_user.roles) == 1 and sys_user.has_role(ROLE.ADMIN.value):
        # nothing needed - leave
        return

    admin_only = Role.query.filter(Role.name == ROLE.ADMIN.value).all()
    sys_user.update_roles(role_list=admin_only, acting_user=sys_user)
    db.session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
