"""empty message

Revision ID: 9f38cc3dee9e
Revises: c4a89e579e00
Create Date: 2016-06-14 15:57:47.268596

"""

# revision identifiers, used by Alembic.
revision = '9f38cc3dee9e'
down_revision = 'c4a89e579e00'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_interventions', sa.Column(
        'provider_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_interventions', 'provider_html')
    ### end Alembic commands ###
