from alembic import op

"""Drop UserObservation unique constraint in favor of history

Revision ID: a22bf5c68d33
Revises: df7f10d6fd60
Create Date: 2018-04-06 04:47:18.518343

"""

# revision identifiers, used by Alembic.
revision = 'a22bf5c68d33'
down_revision = 'df7f10d6fd60'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        u'_user_observation', 'user_observations', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        u'_user_observation', 'user_observations',
        ['user_id', 'observation_id'])
    # ### end Alembic commands ###
