"""Clean up protected roles (again after reset p/w fix)

Revision ID: a33cb61fff11
Revises: e396fb1974ef
Create Date: 2018-05-01 20:13:55.196551

"""
from alembic import op
from sqlalchemy.orm import sessionmaker

Session = sessionmaker()


# revision identifiers, used by Alembic.
revision = 'a33cb61fff11'
down_revision = 'e396fb1974ef'


def upgrade():
    # Users that have registered should not have restricted roles
    # such as `access_on_verify` or `write_only`.  Remove if found
    bind = op.get_bind()
    session = Session(bind=bind)

    # Kill those with set passwords
    session.execute("""
            DELETE FROM user_roles WHERE id IN (
            SELECT user_roles.id FROM users
            JOIN user_roles ON users.id = user_id
            JOIN roles ON roles.id = role_id
            WHERE password IS NOT NULL
            AND roles.name IN ('access_on_verify', 'write_only',
            'promote_without_identity_challenge'))""")

    # .. and those with auth_providers
    session.execute("""
            DELETE FROM user_roles WHERE id IN (
            SELECT user_roles.id FROM users
            JOIN user_roles ON users.id = user_roles.user_id
            JOIN roles ON roles.id = role_id
            JOIN auth_providers ON users.id = auth_providers.user_id
            WHERE roles.name IN ('access_on_verify', 'write_only',
            'promote_without_identity_challenge'))""")
    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
