from alembic import op
import sqlalchemy as sa


"""empty message

Revision ID: a679f493bcdd
Revises: 68c153cf6a02
Create Date: 2017-09-28 12:31:12.590545

"""

# revision identifiers, used by Alembic.
revision = 'a679f493bcdd'
down_revision = '68c153cf6a02'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_jobs', sa.Column('last_status', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_jobs', 'last_status')
    # ### end Alembic commands ###
