"""empty message

Revision ID: a97ce9f7bfc
Revises: 25d491602bf
Create Date: 2015-06-18 18:40:57.553097

"""

# revision identifiers, used by Alembic.
revision = 'a97ce9f7bfc'
down_revision = '25d491602bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'email', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'email')
    ### end Alembic commands ###
