"""empty message

Revision ID: ab32aa0457a8
Revises: 8062d67a91e0
Create Date: 2016-08-24 11:22:46.376711

"""

# revision identifiers, used by Alembic.
revision = 'ab32aa0457a8'
down_revision = '8062d67a91e0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

def strings_from_template():
    """The templates contained static strings we need to push in the db"""

    conn = op.get_bind()
    stmt = """UPDATE interventions SET link_label=:link_label,
    card_html=:card_html WHERE name =:name"""

    # -- SEXUAL_RECOVERY --
    link_label = 'Sexual Recovery'
    card_html = "<p>Learn strategies for developing a new normal in your sex life after treatment for prostate cancer.</p>"
    conn.execute(text(stmt), link_label=link_label, card_html=card_html,
                name='sexual_recovery')

    # -- CARE_PLAN --
    link_label = 'Care Plan'
    card_html = "<p>Organization and support for the many details of life as a prostate cancer survivor</p>"
    conn.execute(text(stmt), link_label=link_label, card_html=card_html,
                name='care_plan')

    stmt = """UPDATE interventions SET description=:description,
    link_label=:link_label, card_html=:card_html WHERE name=:name"""

    # -- DECISION_SUPPORT_P3P --
    description = 'Decision Support tool'
    card_html = " <p>Explore your values, your preferences, and the current medical knowledge to help you discuss your treatment options with your doctors.</p>"
    link_label = "Go to Decision Support"
    conn.execute(text(stmt), description=description,
                 link_label=link_label, card_html=card_html,
                 name='decision_support_p3p')

    # -- SELF_MANAGEMENT --
    description = "Symptom Tracker tool"
    card_html = "<p>Learn about symptoms that are common in men with prostate cancer, and about ways to manage and improve these symptoms.</p>"
    link_label = "Go to Symptom Tracker"
    conn.execute(text(stmt), description=description,
                 link_label=link_label, card_html=card_html,
                 name='self_management')



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interventions', sa.Column('link_label', sa.Text(), nullable=True))
    op.add_column('interventions', sa.Column('status_text', sa.Text(), nullable=True))
    op.alter_column('interventions', column_name='card_url',
                    new_column_name='link_url')
    op.add_column('user_interventions', sa.Column('link_label', sa.Text(), nullable=True))
    op.add_column('user_interventions', sa.Column('link_url', sa.Text(), nullable=True))
    op.add_column('user_interventions', sa.Column('status_text', sa.Text(), nullable=True))
    ### end Alembic commands ###
    strings_from_template()

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_interventions', 'status_text')
    op.drop_column('user_interventions', 'link_url')
    op.drop_column('user_interventions', 'link_label')
    op.alter_column('interventions', column_name='link_url',
                    new_column_name='card_url')
    op.drop_column('interventions', 'status_text')
    op.drop_column('interventions', 'link_label')
    ### end Alembic commands ###
