"""Extend observations and codings as per SDC needs

Revision ID: b513ad8e85b7
Revises: 1675585e7031
Create Date: 2020-11-03 16:19:00.174071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b513ad8e85b7'
down_revision = '1675585e7031'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'codings', sa.Column('extension_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'codings_codings_extension_fk',
        'codings',
        'codings',
        ['extension_id'],
        ['id'])
    op.add_column(
        'observations',
        sa.Column('derived_from', sa.Text(), nullable=True))
    op.add_column(
        'observations',
        sa.Column('value_coding_id', sa.Integer(), nullable=True))
    op.alter_column(
        'observations', 'value_quantity_id',
        existing_type=sa.INTEGER(),
        nullable=True)
    op.create_index(
        op.f('ix_observations_derived_from'),
        'observations',
        ['derived_from'],
        unique=False)
    op.create_foreign_key(
        'observations_value_coding_fk',
        'observations',
        'codings',
        ['value_coding_id'],
        ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'observations_value_coding_fk',
        'observations',
        type_='foreignkey')
    op.drop_index(
        op.f('ix_observations_derived_from'), table_name='observations')
    op.alter_column(
        'observations',
        'value_quantity_id',
        existing_type=sa.INTEGER(),
        nullable=False)
    op.drop_column('observations', 'value_coding_id')
    op.drop_column('observations', 'derived_from')
    op.drop_constraint(
        'codings_codings_extension_fk', 'codings', type_='foreignkey')
    op.drop_column('codings', 'extension_id')
    # ### end Alembic commands ###
