"""Add ResearchStudy

Revision ID: bb82a0b6cb5c
Revises: f93d9608c372
Create Date: 2020-07-30 16:45:56.473053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb82a0b6cb5c'
down_revision = 'f93d9608c372'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_studies',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column(
            'status',
            postgresql.ENUM(
                'active', 'administratively-completed', 'approved',
                'closed-to-accrual', 'closed-to-accrual-and-intervention',
                'completed', 'disapproved', 'in-review',
                'temporarily-closed-to-accrual',
                'temporarily-closed-to-accrual-and-intervention',
                'withdrawn',
                name='research_study_status_enum'),
            server_default='active',
            nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_studies')
    op.execute("DROP TYPE research_study_status_enum")
    # ### end Alembic commands ###
