"""empty message

Revision ID: c04d7e1c0ae
Revises: 510aaa0d1541
Create Date: 2016-03-29 16:15:58.157711

"""

# revision identifiers, used by Alembic.
revision = 'c04d7e1c0ae'
down_revision = '510aaa0d1541'

import sqlalchemy as sa
from alembic import op

old_genders = ('male', 'female', 'undifferentiated')
new_genders = ('male', 'female', 'other', 'unknown')

old_type = sa.Enum(*old_genders, name='genders')
new_type = sa.Enum(*new_genders, name='genders')
tmp_type = sa.Enum(*new_genders, name='_genders')


def upgrade():
    # Create a tempoary "_gender" type, convert and drop the "old" type
    tmp_type.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE users ALTER COLUMN gender TYPE _genders'
               ' USING gender::text::_genders');
    old_type.drop(op.get_bind(), checkfirst=False)
    # Create and convert to the "new" gender type
    new_type.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE users ALTER COLUMN gender TYPE genders'
               ' USING gender::text::genders');
    tmp_type.drop(op.get_bind(), checkfirst=False)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
