"""empty message

Revision ID: c070976dc8fb
Revises: ab32aa0457a8
Create Date: 2016-08-29 09:24:14.788987

"""

# revision identifiers, used by Alembic.
revision = 'c070976dc8fb'
down_revision = 'ab32aa0457a8'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_consent',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('organization_id', sa.Integer(), nullable=False),
                    sa.Column('audit_id', sa.Integer(), nullable=False),
                    sa.Column('expires', sa.DateTime(), nullable=False),
                    sa.Column('agreement_url', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(['audit_id'], ['audit.id'], ),
                    sa.ForeignKeyConstraint(['organization_id'], [
                                            'organizations.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_consent')
    ### end Alembic commands ###
