from alembic import op
import sqlalchemy as sa

"""empty message

Revision ID: c0ab21bc488b
Revises: 72dcf1946d3f
Create Date: 2017-12-14 13:28:16.602934

"""

# revision identifiers, used by Alembic.
revision = 'c0ab21bc488b'
down_revision = '72dcf1946d3f'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tou', sa.Column('active', sa.Boolean(),
                                   server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tou', 'active')
    # ### end Alembic commands ###
