"""User Preferences table

Revision ID: c1adb8e69b50
Revises: 4737a563e3f9
Create Date: 2020-02-11 09:56:54.341004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1adb8e69b50'
down_revision = '4737a563e3f9'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column(
        'preference_name',
        sa.Enum('suppress_email', name='user_preference_types'),
        nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint(
        'user_id', 'preference_name', name='_user_preference_uniq')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    op.execute("DROP TYPE user_preference_types")
    # ### end Alembic commands ###
