"""remove questionnaire_response.authored column

Revision ID: c243aa77e9e4
Revises: 167b44b795e4
Create Date: 2021-01-25 13:48:37.443637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c243aa77e9e4'
down_revision = '167b44b795e4'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionnaire_responses', 'authored')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'questionnaire_responses',
        sa.Column(
            'authored',
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True))
    # ### end Alembic commands ###
