"""empty message

Revision ID: cbdadee4a05f
Revises: 9f38cc3dee9e
Create Date: 2016-06-14 17:55:57.526196

"""

# revision identifiers, used by Alembic.
revision = 'cbdadee4a05f'
down_revision = '9f38cc3dee9e'

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('email_invites', 'email_messages')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('email_messages', 'email_invites')
    ### end Alembic commands ###
