"""user.remember_me_cookie

Revision ID: ccb67176c56f
Revises: 2f125954b69a
Create Date: 2023-05-30 16:00:04.693362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb67176c56f'
down_revision = '2f125954b69a'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('remember_me_cookie', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'remember_me_cookie')
    # ### end Alembic commands ###
