"""add missing constraint to trigger_states table

Revision ID: cf586ed4f043
Revises: 80c3b1e96c45
Create Date: 2024-03-20 17:17:39.403806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf586ed4f043'
down_revision = '80c3b1e96c45'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_trigger_states_user_state_visit_month', 'trigger_states', ['user_id', 'state', 'visit_month'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_trigger_states_user_state_visit_month', 'trigger_states', type_='unique')
    # ### end Alembic commands ###
