"""empty message

Revision ID: cf9e2925919c
Revises: b68a125b8470
Create Date: 2017-03-07 22:04:03.740631

"""

# revision identifiers, used by Alembic.
revision = 'cf9e2925919c'
down_revision = 'b68a125b8470'

from alembic import op
import sqlalchemy as sa


# see https://bitbucket.org/zzzeek/alembic/issues/123/a-way-to-run-non-transactional-ddl
def upgrade():
    connection = None
    if not op.get_context().as_sql:
        connection = op.get_bind()
        connection.execution_options(isolation_level='AUTOCOMMIT')

    op.execute("ALTER TYPE auth_methods ADD VALUE IF NOT EXISTS 'service_token_authenticated'")

    if connection is not None:
        connection.execution_options(isolation_level='READ_COMMITTED')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
