"""empty message

Revision ID: cfb3cf41a07a
Revises: c070976dc8fb
Create Date: 2016-08-30 16:21:04.035292

"""

# revision identifiers, used by Alembic.
revision = 'cfb3cf41a07a'
down_revision = 'c070976dc8fb'

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import text


def upgrade():
    # for any users without an email, bring over the username if avail
    conn = op.get_bind()
    result = conn.execute(text("""SELECT id, username FROM users WHERE email is
                               null AND username != 'Anonymous'"""))
    results = result.fetchall()
    for r in results:
        conn.execute(text("""UPDATE users SET email=:username WHERE id=:id"""),
                     username=r[1], id=r[0])

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(
        length=64), autoincrement=False, nullable=True))
    ### end Alembic commands ###
