""" Truncate microseconds from user_consent.acceptance_dates

Revision ID: d561999e9b42
Revises: 265e7dc4c1a5
Create Date: 2019-04-25 16:24:00.913233

"""
from portal.database import db
from portal.models.user_consent import UserConsent

# revision identifiers, used by Alembic.
revision = 'd561999e9b42'
down_revision = '265e7dc4c1a5'


def upgrade():
    # No easy way to query for those in need, just whip through and fix
    patch = {}
    for uc in UserConsent.query.filter(
            UserConsent.acceptance_date.isnot(None)):
        wo_micro = uc.acceptance_date.replace(microsecond=0)
        if wo_micro != uc.acceptance_date:
            patch[uc] = wo_micro

    print('found {} needing attention'.format(len(patch)))

    # Outside of query loop, make the necessary changes
    for uc, ad_wo_micro in patch.items():
        uc.acceptance_date = ad_wo_micro

    db.session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
