from alembic import op
import sqlalchemy as sa

"""empty message

Revision ID: e503ae1c261a
Revises: a031e26dc1bd
Create Date: 2018-08-14 16:05:28.104848

"""

# revision identifiers, used by Alembic.
revision = 'e503ae1c261a'
down_revision = 'a031e26dc1bd'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'last_password_verification_failure',
            sa.DateTime(),
            nullable=True
        )
    )

    op.add_column(
        'users',
        sa.Column(
            'password_verification_failures',
            sa.Integer(),
            nullable=False,
            server_default=sa.text('0')
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_verification_failures')
    op.drop_column('users', 'last_password_verification_failure')
    # ### end Alembic commands ###
