"""empty message

Revision ID: e7682ee1276f
Revises: 1ab82c60f309
Create Date: 2017-02-16 12:49:50.670278

"""

# revision identifiers, used by Alembic.
revision = 'e7682ee1276f'
down_revision = '1ab82c60f309'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE roles SET name='staff' WHERE name='provider'")
    op.alter_column('user_interventions', 'provider_html',
                    new_column_name='staff_html')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE roles SET name='provider' WHERE name='staff'")
    op.alter_column('user_interventions', 'staff_html',
                    new_column_name='provider_html')
    ### end Alembic commands ###
