"""empty message

Revision ID: e7682ee1276f
Revises: 1ab82c60f309
Create Date: 2017-02-16 12:49:50.670278

"""

# revision identifiers, used by Alembic.
revision = 'e7682ee1276f'
down_revision = '1ab82c60f309'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE roles SET name='staff' WHERE name='provider'")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE roles SET name='provider' WHERE name='staff'")
    ### end Alembic commands ###
