"""empty message

Revision ID: ef6590c54073
Revises: 23b47479c442
Create Date: 2017-05-23 14:04:09.892330

"""

# revision identifiers, used by Alembic.
revision = 'ef6590c54073'
down_revision = '23b47479c442'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounter_codings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('encounter_id', sa.Integer(), nullable=False),
                    sa.Column('coding_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['coding_id'], ['codings.id'], ),
                    sa.ForeignKeyConstraint(
                        ['encounter_id'], ['encounters.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('encounter_codings')
    # ### end Alembic commands ###
