"""Extend user_interventsion.access to include `subscribed`

Revision ID: ef6fe47c40d1
Revises: e396fb1974ef
Create Date: 2018-05-01 11:36:57.128375

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ef6fe47c40d1'
down_revision = 'e396fb1974ef'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("commit")  # get around transaction warnings by faking a commit
    op.execute("ALTER TYPE access ADD VALUE IF NOT EXISTS 'subscribed'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # postgres doesn't support dropping an enum value - not worth the downgrade.
    pass
    # ### end Alembic commands ###
