import sqlalchemy as sa
from alembic import op

"""empty message

Revision ID: eff963021768
Revises: 30d760f9103c
Create Date: 2017-09-12 10:18:21.692720

"""

# revision identifiers, used by Alembic.
revision = 'eff963021768'
down_revision = '30d760f9103c'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('COMMIT')
    op.execute(
        "ALTER TYPE classification_enum ADD VALUE 'followup' AFTER "
        "'baseline'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # shameful timecrunch - omitting painful step to remove an enum
    # value.  howto:  https://stackoverflow.com/a/14845740
    pass
    # ### end Alembic commands ###
