import sqlalchemy as sa
from alembic import op

"""empty message

Revision ID: f32ba62f1e77
Revises: 88f0e897cca0
Create Date: 2017-09-18 11:41:52.944434

"""

# revision identifiers, used by Alembic.
revision = 'f32ba62f1e77'
down_revision = '88f0e897cca0'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaire_responses', sa.Column('qb_iteration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionnaire_responses', 'qb_iteration')
    # ### end Alembic commands ###
