"""empty message

Revision ID: fb87044ded54
Revises: 7a19bd0ad53a
Create Date: 2016-10-17 17:48:57.912879

"""

# revision identifiers, used by Alembic.
revision = 'fb87044ded54'
down_revision = '7a19bd0ad53a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_consents',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('organization_id', sa.Integer(), nullable=False),
                    sa.Column('audit_id', sa.Integer(), nullable=False),
                    sa.Column('expires', sa.DateTime(), nullable=False),
                    sa.Column('agreement_url', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(['audit_id'], ['audit.id'], ),
                    sa.ForeignKeyConstraint(['organization_id'], [
                                            'organizations.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('user_consent')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_consent',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('user_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('organization_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('audit_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('expires', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=False),
                    sa.Column('agreement_url', sa.TEXT(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['audit_id'], [u'audit.id'], name=u'user_consent_audit_id_fkey'),
                    sa.ForeignKeyConstraint(['organization_id'], [
                        u'organizations.id'], name=u'user_consent_organization_id_fkey'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], [u'users.id'], name=u'user_consent_user_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name=u'user_consent_pkey')
                    )
    op.drop_table('user_consents')
    ### end Alembic commands ###
