"""Add research_study_id (and missing index) to qb_timeline

Revision ID: fbc3fb59ffb8
Revises: 1977c23a53c8
Create Date: 2020-08-06 14:15:37.678144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc3fb59ffb8'
down_revision = '30f20e54eb5c'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qb_timeline', sa.Column('research_study_id', sa.Integer()))
    op.execute('UPDATE qb_timeline SET research_study_id = 0')
    op.alter_column('qb_timeline', 'research_study_id', nullable=False)

    op.create_index(
        op.f('ix_qb_timeline_research_study_id'),
        'qb_timeline',
        ['research_study_id'],
        unique=False)
    op.create_index(
        op.f('ix_qb_timeline_user_id'),
        'qb_timeline',
        ['user_id'],
        unique=False)
    op.create_foreign_key(
        op.f('qb_timeline_research_study_id_fkey'),
        'qb_timeline',
        'research_studies',
        ['research_study_id'],
        ['id'],
        ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('qb_timeline_research_study_id_fkey'),
        'qb_timeline',
        type_='foreignkey')
    op.drop_index(op.f('ix_qb_timeline_user_id'), table_name='qb_timeline')
    op.drop_index(
        op.f('ix_qb_timeline_research_study_id'), table_name='qb_timeline')
    op.drop_column('qb_timeline', 'research_study_id')
    # ### end Alembic commands ###
